[versions]
kotlin = "2.0.21"
composeMultiplatform = "1.7.3"
jediterm = "3.74"
pty4j = "0.13.12"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

[libraries]
jediterm-core = { module = "org.jetbrains.jediterm:jediterm-core", version.ref = "jediterm" }
jediterm-ui = { module = "org.jetbrains.jediterm:jediterm-ui", version.ref = "jediterm" }
pty4j = { module = "org.jetbrains.pty4j:pty4j", version.ref = "pty4j" }
