package com.multiviewer.parser

// Mobile Country Code -> country/geographical area name, sourced directly from the official
// ITU-T E.212 Annex A ("List of Mobile Country or Geographical Area Codes"), NOT a secondary
// source: a prior phase of this app found a real error in a Wikipedia-sourced version of this
// same table (MCC 450 and 467 -- South and North Korea -- were swapped). This table was
// extracted from the ITU's own PDF (https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.212A-2017-PDF-E.pdf,
// "Annex to ITU Operational Bulletin No. 1117 - 1.II.2017", numerical-order section) via
// `pdftotext -layout`, confirming MCC 450 = "Korea (Republic of)" and 467 = "Democratic
// People's Republic of Korea" against the raw extracted text -- the swap in the earlier,
// never-shipped Wikipedia-sourced attempt was real, this source is correct. A few codes are
// legitimately shared between multiple named territories in the official table (e.g. 340
// between Guadeloupe and Martinique, 362 between three Dutch Caribbean territories) -- those
// are combined into a single "/"-joined display string rather than picking one arbitrarily.
//
// This table reflects the ITU's 2017 edition. ITU republishes Annex A periodically; refreshing
// this table means re-running the same extraction against the current Annex A PDF (search
// itu.int for "ITU-T E.212 Annex A list of mobile country codes") and diffing against this file.
internal val MCC_COUNTRY_NAMES: Map<Int, String> = mapOf(
    202 to "Greece",
    204 to "Netherlands (Kingdom of the)",
    206 to "Belgium",
    208 to "France",
    212 to "Monaco (Principality of)",
    213 to "Andorra (Principality of)",
    214 to "Spain",
    216 to "Hungary",
    218 to "Bosnia and Herzegovina",
    219 to "Croatia (Republic of)",
    220 to "Serbia (Republic of)",
    221 to "Kosovo*",
    222 to "Italy",
    225 to "Vatican City State",
    226 to "Romania",
    228 to "Switzerland (Confederation of)",
    230 to "Czech Republic",
    231 to "Slovak Republic",
    232 to "Austria",
    234 to "United Kingdom of Great Britain and Northern Ireland",
    235 to "United Kingdom of Great Britain and Northern Ireland",
    238 to "Denmark",
    240 to "Sweden",
    242 to "Norway",
    244 to "Finland",
    246 to "Lithuania (Republic of)",
    247 to "Latvia (Republic of)",
    248 to "Estonia (Republic of)",
    250 to "Russian Federation",
    255 to "Ukraine",
    257 to "Belarus (Republic of)",
    259 to "Moldova (Republic of)",
    260 to "Poland (Republic of)",
    262 to "Germany (Federal Republic of)",
    266 to "Gibraltar",
    268 to "Portugal",
    270 to "Luxembourg",
    272 to "Ireland",
    274 to "Iceland",
    276 to "Albania (Republic of)",
    278 to "Malta",
    280 to "Cyprus (Republic of)",
    282 to "Georgia",
    283 to "Armenia (Republic of)",
    284 to "Bulgaria (Republic of)",
    286 to "Turkey",
    288 to "Faroe Islands",
    290 to "Greenland (Denmark)",
    292 to "San Marino (Republic of)",
    293 to "Slovenia (Republic of)",
    294 to "The Former Yugoslav Republic of Macedonia",
    295 to "Liechtenstein (Principality of)",
    297 to "Montenegro",
    302 to "Canada",
    308 to "Saint Pierre and Miquelon (Collectivité territoriale de la République française)",
    310 to "United States of America",
    311 to "United States of America",
    312 to "United States of America",
    313 to "United States of America",
    314 to "United States of America",
    315 to "United States of America",
    316 to "United States of America",
    330 to "Puerto Rico",
    332 to "United States Virgin Islands",
    334 to "Mexico",
    338 to "Jamaica",
    340 to "Guadeloupe (French Department of) / Martinique (French Department of)",
    342 to "Barbados",
    344 to "Antigua and Barbuda",
    346 to "Cayman Islands",
    348 to "British Virgin Islands",
    350 to "Bermuda",
    352 to "Grenada",
    354 to "Montserrat",
    356 to "Saint Kitts and Nevis",
    358 to "Saint Lucia",
    360 to "Saint Vincent and the Grenadines",
    362 to "Curaçao / Sint Maarten (Dutch part) / Bonaire, Sint Eustatius and Saba",
    363 to "Aruba",
    364 to "Bahamas (Commonwealth of the)",
    365 to "Anguilla",
    366 to "Dominica (Commonwealth of)",
    368 to "Cuba",
    370 to "Dominican Republic",
    372 to "Haiti (Republic of)",
    374 to "Trinidad and Tobago",
    376 to "Turks and Caicos Islands",
    400 to "Azerbaijan (Republic of)",
    401 to "Kazakhstan (Republic of)",
    402 to "Bhutan (Kingdom of)",
    404 to "India (Republic of)",
    405 to "India (Republic of)",
    406 to "India (Republic of)",
    410 to "Pakistan (Islamic Republic of)",
    412 to "Afghanistan",
    413 to "Sri Lanka (Democratic Socialist Republic of)",
    414 to "Myanmar (the Republic of the Union of)",
    415 to "Lebanon",
    416 to "Jordan (Hashemite Kingdom of)",
    417 to "Syrian Arab Republic",
    418 to "Iraq (Republic of)",
    419 to "Kuwait (State of)",
    420 to "Saudi Arabia (Kingdom of)",
    421 to "Yemen (Republic of)",
    422 to "Oman (Sultanate of)",
    424 to "United Arab Emirates",
    425 to "Israel (State of)",
    426 to "Bahrain (Kingdom of)",
    427 to "Qatar (State of)",
    428 to "Mongolia",
    429 to "Nepal (Federal Democratic Republic of)",
    430 to "United Arab Emirates",
    431 to "United Arab Emirates",
    432 to "Iran (Islamic Republic of)",
    434 to "Uzbekistan (Republic of)",
    436 to "Tajikistan (Republic of)",
    437 to "Kyrgyz Republic",
    438 to "Turkmenistan",
    440 to "Japan",
    441 to "Japan",
    450 to "Korea (Republic of)",
    452 to "Viet Nam (Socialist Republic of)",
    454 to "Hong Kong, China",
    455 to "Macao, China",
    456 to "Cambodia (Kingdom of)",
    457 to "Lao People's Democratic Republic",
    460 to "China (People's Republic of)",
    461 to "China (People's Republic of)",
    466 to "Taiwan, China",
    467 to "Democratic People's Republic of Korea",
    470 to "Bangladesh (People's Republic of)",
    472 to "Maldives (Republic of)",
    502 to "Malaysia",
    505 to "Australia",
    510 to "Indonesia (Republic of)",
    514 to "Timor-Leste (Democratic Republic of)",
    515 to "Philippines (Republic of the)",
    520 to "Thailand",
    525 to "Singapore (Republic of)",
    528 to "Brunei Darussalam",
    530 to "New Zealand",
    536 to "Nauru (Republic of)",
    537 to "Papua New Guinea",
    539 to "Tonga (Kingdom of)",
    540 to "Solomon Islands",
    541 to "Vanuatu (Republic of)",
    542 to "Fiji (Republic of)",
    543 to "Wallis and Futuna (Territoire français d'outre-mer)",
    544 to "American Samoa",
    545 to "Kiribati (Republic of)",
    546 to "New Caledonia (Territoire français d'outre-mer)",
    547 to "French Polynesia (Territoire français d'outre-mer)",
    548 to "Cook Islands",
    549 to "Samoa (Independent State of)",
    550 to "Micronesia (Federated States of)",
    551 to "Marshall Islands (Republic of the)",
    552 to "Palau (Republic of)",
    553 to "Tuvalu",
    554 to "Tokelau",
    555 to "Niue",
    602 to "Egypt (Arab Republic of)",
    603 to "Algeria (People's Democratic Republic of)",
    604 to "Morocco (Kingdom of)",
    605 to "Tunisia",
    606 to "Libya",
    607 to "Gambia (Republic of the)",
    608 to "Senegal (Republic of)",
    609 to "Mauritania (Islamic Republic of)",
    610 to "Mali (Republic of)",
    611 to "Guinea (Republic of)",
    612 to "Côte d'Ivoire (Republic of)",
    613 to "Burkina Faso",
    614 to "Niger (Republic of the)",
    615 to "Togolese Republic",
    616 to "Benin (Republic of)",
    617 to "Mauritius (Republic of)",
    618 to "Liberia (Republic of)",
    619 to "Sierra Leone",
    620 to "Ghana",
    621 to "Nigeria (Federal Republic of)",
    622 to "Chad (Republic of)",
    623 to "Central African Republic",
    624 to "Cameroon (Republic of)",
    625 to "Cabo Verde (Republic of)",
    626 to "Sao Tome and Principe (Democratic Republic of)",
    627 to "Equatorial Guinea (Republic of)",
    628 to "Gabonese Republic",
    629 to "Congo (Republic of the)",
    630 to "Democratic Republic of the Congo",
    631 to "Angola (Republic of)",
    632 to "Guinea-Bissau (Republic of)",
    633 to "Seychelles (Republic of)",
    634 to "Sudan (Republic of the)",
    635 to "Rwanda (Republic of)",
    636 to "Ethiopia (Federal Democratic Republic of)",
    637 to "Somalia (Federal Republic of)",
    638 to "Djibouti (Republic of)",
    639 to "Kenya (Republic of)",
    640 to "Tanzania (United Republic of)",
    641 to "Uganda (Republic of)",
    642 to "Burundi (Republic of)",
    643 to "Mozambique (Republic of)",
    645 to "Zambia (Republic of)",
    646 to "Madagascar (Republic of)",
    647 to "French Departments and Territories in the Indian Ocean",
    648 to "Zimbabwe (Republic of)",
    649 to "Namibia (Republic of)",
    650 to "Malawi",
    651 to "Lesotho (Kingdom of)",
    652 to "Botswana (Republic of)",
    653 to "Swaziland (Kingdom of)",
    654 to "Comoros (Union of the)",
    655 to "South Africa (Republic of)",
    657 to "Eritrea",
    658 to "Saint Helena, Ascension and Tristan da Cunha",
    659 to "South Sudan (Republic of)",
    702 to "Belize",
    704 to "Guatemala (Republic of)",
    706 to "El Salvador (Republic of)",
    708 to "Honduras (Republic of)",
    710 to "Nicaragua",
    712 to "Costa Rica",
    714 to "Panama (Republic of)",
    716 to "Peru",
    722 to "Argentine Republic",
    724 to "Brazil (Federative Republic of)",
    730 to "Chile",
    732 to "Colombia (Republic of)",
    734 to "Venezuela (Bolivarian Republic of)",
    736 to "Bolivia (Plurinational State of)",
    738 to "Guyana",
    740 to "Ecuador",
    742 to "French Guiana (French Department of)",
    744 to "Paraguay (Republic of)",
    746 to "Suriname (Republic of)",
    748 to "Uruguay (Eastern Republic of)",
    750 to "Falkland Islands (Malvinas)",
    901 to "International Mobile, shared code",
)
